### ISSUE TITLE
Missing .Rmd for Detecting cell-cycle stage difference in glioblastoma cells

### ISSUE THREAD

**Issue by 3rweh** [dleelab/iasvaExamples#1]
Hi!

First of all I just want to say thank you for an excellent Git, and an exciting research!

I wonder if there is any available *.Rmd* for **Detecting cell-cycle stage difference in glioblastoma cells**? All your [vignettes](https://github.com/dleelab/iasvaExamples/tree/268983524d3aee232c1bf032e8dd8993bcfb4fc3/vignettes) have complete *.Rmd* scripts, but not the one for cell-cycle stages.

Best regards,

Erik Hedman

**Comment by dleelab** [comment]
Hi Erik,

You can find the html and Rmd files for the cell-cycle example from the
link below:

https://raw.githubusercontent.com/dleelab/iasvaExamples/master/analysis/hidden_heterogeneity_glioblastoma.Rmd
https://dleelab.github.io/iasvaExamples/hidden_heterogeneity_glioblastoma.html

Thanks, and please let us know if you have any questions or suggestions!

Best,
Don
